### ISSUE TITLE
This event loop already running -- error using shelve cache example

### ISSUE THREAD

**Issue by mwiebold** [wrobell/geotiler#18]
When running the example ex-shelvecache.py, geotiler 0.13, Python 3.6.4, iPython 6.2.1. 

```
Traceback (most recent call last):

  File "<ipython-input-8-b158063d5933>", line 1, in <module>
    runfile('C:/Users/mw/Desktop/geotiler_test.py', wdir='C:/Users/mw/Desktop')

  File "C:\Users\mw\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\mw\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/mw/Desktop/geotiler_test.py", line 116, in <module>
    img = render_map(mm)

  File "C:\Users\mw\AppData\Local\Continuum\anaconda3\lib\site-packages\geotiler\map.py", line 374, in render_map
    return loop.run_until_complete(task)

  File "C:\Users\mw\AppData\Local\Continuum\anaconda3\lib\asyncio\base_events.py", line 454, in run_until_complete
    self.run_forever()

  File "C:\Users\mw\AppData\Local\Continuum\anaconda3\lib\asyncio\base_events.py", line 408, in run_forever
    raise RuntimeError('This event loop is already running')

RuntimeError: This event loop is already running
```

**Comment by mwiebold** [comment]
Not an expert at asyncio, but it looks like ipython or ipykernel or something already has a loop running. I tried attaching the task to the loop using create_task or expect_future, but the task always was listed as pending. Any way to run this without asyncio?

**Comment by wrobell** [comment]
I believe you are hitting this problem: https://github.com/ipython/ipython/issues/11030. See also https://github.com/ipython/ipython/issues/9166.
