### ISSUE TITLE
Missing images in documentation

### ISSUE THREAD

**Issue by heitorPB** [wrobell/geotiler#21]
`sphinx-build doc/ _build/` complains that these images were not found:

- /home/h/projects/geotiler/doc/cmd.rst:: WARNING: image file not readable: map-bluemarble.png
- /home/h/projects/geotiler/doc/cmd.rst:: WARNING: image file not readable: map-path.png
- /home/h/projects/geotiler/doc/usage.rst:: WARNING: image file not readable: map-osm.png
- /home/h/projects/geotiler/doc/usage.rst:: WARNING: image file not readable: map-stamen-toner.png

Indeed, they are not there...

**Comment by wrobell** [comment]
You can generate them with `make doc` command. Please, see the `Makefile` file also.

**Comment by heitorPB** [comment]
It would be nice to have some instructions somewhere. The Makefile outputs only errors when I run it.

Could you also add a reference to the online docs somewhere? https://wrobell.dcmod.org/geotiler/

**Comment by wrobell** [comment]
What are the errors?

**Comment by heitorPB** [comment]
```
$ make doc
./bin/geotiler-lint --cache redis -c -6.069 53.390 -s 512 512 -z 15 doc/map-osm.png
configuration file /home/h/.config/geotiler/geotiler.ini does not exist
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/usr/lib/python3.7/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/usr/lib/python3.7/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/usr/lib/python3.7/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/lib/python3.7/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/usr/lib/python3.7/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/usr/lib/python3.7/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/usr/lib/python3.7/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/geotiler-lint", line 101, in <module>
    img = geotiler.render_map(map, downloader=downloader)
  File "/usr/lib/python3.7/site-packages/geotiler/map.py", line 374, in render_map
    return loop.run_until_complete(task)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/usr/lib/python3.7/site-packages/geotiler/map.py", line 397, in render_map_async
    return await render_image(map, tiles)
  File "/usr/lib/python3.7/site-packages/geotiler/tile/img.py", line 67, in render_image
    async for tile in tiles:
  File "/usr/lib/python3.7/site-packages/geotiler/map.py", line 396, in <genexpr>
    tiles = (t async for t in tiles)
  File "/usr/lib/python3.7/site-packages/geotiler/cache.py", line 79, in caching_downloader
    for tg in groups:
  File "cytoolz/itertoolz.pyx", line 1047, in cytoolz.itertoolz.partition_all.__next__
  File "/usr/lib/python3.7/site-packages/geotiler/util.py", line 33, in <genexpr>
    tiles = (print(t) for t in tiles)
  File "/usr/lib/python3.7/site-packages/geotiler/cache.py", line 47, in <genexpr>
    tiles = (t._replace(img=get(t.url)) for t in tiles)
  File "/usr/lib/python3.7/site-packages/redis/client.py", line 976, in get
    return self.execute_command('GET', name)
  File "/usr/lib/python3.7/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/usr/lib/python3.7/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/lib/python3.7/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/usr/lib/python3.7/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
make: *** [Makefile:17: .map-stamp] Error 1
```

**Comment by wrobell** [comment]
Please take a look at the Makefile and the errors. You need Redis to be started - no point of constantly fetching maps from the servers during development process. ;)

Will try to write some development intro soon.

**Comment by heitorPB** [comment]
It is interesting that the command `$ geotiler-route hike.gpx hike.png` also fails with the same redis errors. After running a redis-server it worked, but I have no idea what redis is ^^
